# Generated by Django 2.1.4 on 2018-12-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Windforecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_time', models.DateTimeField()),
                ('runtime', models.DateTimeField()),
                ('wind_max', models.FloatField()),
                ('wind_average', models.FloatField()),
                ('wind_angle', models.FloatField()),
                ('test', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WindMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('runtime', models.DateTimeField(unique=True)),
                ('wind_max', models.FloatField()),
                ('wind_average', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='windforecast',
            unique_together={('forecast_time', 'runtime')},
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windhunt.Question'),
        ),
    ]
