# Generated by Django 2.1.4 on 2018-12-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windforecast',
            name='test',
        ),
    ]
