# Generated by Django 2.1.4 on 2018-12-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0002_remove_windforecast_test'),
    ]

    operations = [
    	migrations.RenameModel('windforecast', 'windSuperforecast')
    ]
