# Generated by Django 2.1.4 on 2018-12-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0004_auto_20181215_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='windforecast',
            unique_together=set(),
        ),
    ]
