# Generated by Django 2.1.4 on 2018-12-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0005_auto_20181215_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindForecast',
        ),
    ]
