# Generated by Django 2.1.4 on 2018-12-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0008_auto_20181215_1236'),
    ]

    operations = [

    ]
