# Generated by Django 2.1.4 on 2018-12-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0009_auto_20181215_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindForecast',
        ),
    ]
