# Generated by Django 2.1.4 on 2018-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0010_delete_windforecast'),
    ]

    operations = [

    ]
