# Generated by Django 2.1.4 on 2018-12-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windhunt', '0014_auto_20181215_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WindForecas',
            new_name='WindForecast',
        ),
    ]
